# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build express-streamer`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t express-streamer`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system express-streamer && \
          adduser --system -G express-streamer express-streamer

COPY dist/express-streamer express-streamer
RUN chown -R express-streamer:express-streamer .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.

# install packages into express-stream folder and ignore dev packages
RUN npm --prefix express-streamer --omit=dev -f install

CMD [ "node", "express-streamer" ]
